# Generated by Django 6.0 on 2026-01-07 00:47

from django.db import migrations, models



def remove_duplicates(apps, schema_editor):
    User = apps.get_model('users', 'User')
    from django.db.models import Count
    
    # Find emails with duplicates
    duplicates = User.objects.values('email').annotate(email_count=Count('email')).filter(email_count__gt=1)
    
    for entry in duplicates:
        email = entry['email']
        users = User.objects.filter(email=email).order_by('-date_joined')
        
        # Keep the most recent one regular, rename others
        # Skip the first one (most recent)
        for user in users[1:]:
            user.email = f"duplicate_{user.id}_{user.email}"
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_superuser'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
