name: Next.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Lint
      run: npm run lint
      
    - name: Build and Typecheck
      env:
        NEXT_PUBLIC_API_URL: "http://localhost:8000"
        NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: "pk_test_mock"
      run: npm run build
